# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-04-17 06:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0002_detailinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bankNo', models.CharField(max_length=64, verbose_name='卡号')),
                ('bank', models.IntegerField(choices=[(0, '未绑定'), (1, '中国建设银行'), (2, '中国农业银行'), (3, '招商银行'), (4, '中国银行')], default=0, verbose_name='银行')),
                ('bankpwd', models.CharField(max_length=200, verbose_name='交易密码')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '银行信息列表',
                'verbose_name_plural': '银行信息',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='消息内容')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='时间')),
                ('isRead', models.BooleanField(default=False, verbose_name='是否已读')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '消息记录列表',
                'verbose_name_plural': '消息记录',
            },
        ),
        migrations.AlterModelOptions(
            name='detailinfo',
            options={'verbose_name': '用户信息列表', 'verbose_name_plural': '用户信息'},
        ),
    ]
